import AddLocationAltIcon from '@mui/icons-material/AddLocationAlt';

import runtimeConfig from '../../config/runtime';
import { METERS_PER_MILE } from '../../utils/geo';

export const pageConfig = {
  id: 'debug-console',
  label: 'DEBUG_CONSOLE',
  icon: AddLocationAltIcon,
  path: '/debug-console',
  order: 2,
  protected: true,
  showInNav: true
};

export const EXPERIMENT_SCREENS = [];
export const EXPERIMENT_TAB_ID = 'troy-experiment';
export const EXPERIMENT_TITLE = "Troy's Dumb Experiment";
export const LIVE_CHAT_TAB_ID = 'live-chat';
export const ACCOUNT_SWAP_TAB_ID = 'account-swap';
export const CHAT_VIS_TAB_ID = 'chat-visualization';
export const STORAGE_TAB_ID = 'storage';

export const DEFAULT_AVATAR_PATH = '/images/profile/profile-01.jpg';
export const DEFAULT_BANNER_PATH = '/images/background/background-01.jpg';
export const BAD_USERS_FALLBACK_AVATAR = DEFAULT_AVATAR_PATH;

export const INITIAL_COORDINATES = {
  latitude: '33.7838',
  longitude: '-118.1136'
};

export const DEFAULT_LOCATION_COORDINATES = {
  latitude: Number.parseFloat(INITIAL_COORDINATES.latitude) || 33.7838,
  longitude: Number.parseFloat(INITIAL_COORDINATES.longitude) || -118.1136
};

export const DEFAULT_LOCATION_ACCURACY = 10;
export const DEFAULT_LOCATION_TELEPORT_KEY = 'default-location';

export const LOCATION_SOURCE_OPTIONS = ['web', 'ios', 'android', 'background'];

export const ACCOUNT_STATUS_OPTIONS = ['active', 'inactive', 'suspended', 'deleted'];

export const UPDATE_TYPE_OPTIONS = [
  'new-pin',
  'badge-earned',
  'location-update',
  'admin-note',
  'badge-revoked',
  'moderation-warning'
];

export const DEFAULT_SPOOF_STEP_MILES = 2;
export const SPOOF_MIN_MILES = 0.25;
export const SPOOF_MAX_MILES = 5;
export const SPOOF_STEP_INCREMENT = 0.25;

const GRID_CENTER = { latitude: 33.7839, longitude: -118.1142 };
const GRID_ROWS = 5;
const GRID_COLS = 5;
const GRID_SPACING_MILES = 2;
const GRID_CELL_RADIUS_METERS = 2600;
const GRID_CELL_DESCRIPTION = 'Autogenerated overlap grid cell for CSULB proximity demos.';

const milesToLatOffset = (miles) => miles / 69;
const milesToLonOffset = (miles, latitudeDegrees) =>
  miles / (69 * Math.cos((latitudeDegrees * Math.PI) / 180));

const GRID_LAT_OFFSET = milesToLatOffset(GRID_SPACING_MILES);
const GRID_LON_OFFSET = milesToLonOffset(GRID_SPACING_MILES, GRID_CENTER.latitude);

const buildGridPresets = () => {
  const presets = [];
  const rowOffset = Math.floor(GRID_ROWS / 2);
  const colOffset = Math.floor(GRID_COLS / 2);

  for (let row = 0; row < GRID_ROWS; row += 1) {
    for (let col = 0; col < GRID_COLS; col += 1) {
      const latitude = Number(
        (GRID_CENTER.latitude + (row - rowOffset) * GRID_LAT_OFFSET).toFixed(6)
      );
      const longitude = Number(
        (GRID_CENTER.longitude + (col - colOffset) * GRID_LON_OFFSET).toFixed(6)
      );
      const label = `CSULB Grid R${row + 1}C${col + 1}`;

      presets.push({
        key: `csulb-grid-r${row + 1}c${col + 1}`,
        label,
        name: label,
        aliases: [label],
        description: GRID_CELL_DESCRIPTION,
        latitude,
        longitude,
        accuracy: 8,
        radiusMeters: GRID_CELL_RADIUS_METERS
      });
    }
  }

  return presets;
};

const GRID_PRESETS = buildGridPresets();

const gridTeleportAnchor = (row, col, options = {}) => {
  const preset = GRID_PRESETS.find(
    (cell) => cell.key === `csulb-grid-r${row}c${col}`
  );
  if (!preset) {
    return null;
  }
  return {
    key: options.key ?? `csulb-grid-r${row}c${col}`,
    label: options.label ?? `Teleport to ${preset.label}`,
    latitude: preset.latitude,
    longitude: preset.longitude,
    accuracy: preset.accuracy,
    statusMessage:
      options.statusMessage ?? `Location spoofed to ${preset.label}.`
  };
};

export const LIVE_CHAT_ROOM_PRESETS = GRID_PRESETS;

const GRID_TELEPORT_PRESETS = [
  gridTeleportAnchor(1, 1, { key: 'grid-nw', label: 'Teleport to NW grid cell' }),
  gridTeleportAnchor(1, 5, { key: 'grid-ne', label: 'Teleport to NE grid cell' }),
  gridTeleportAnchor(3, 3, {
    key: 'grid-center',
    label: 'Teleport to CSULB grid center',
    statusMessage: 'Location spoofed to the CSULB grid center.'
  }),
  gridTeleportAnchor(5, 1, { key: 'grid-sw', label: 'Teleport to SW grid cell' }),
  gridTeleportAnchor(5, 5, { key: 'grid-se', label: 'Teleport to SE grid cell' })
].filter(Boolean);

export const TELEPORT_PRESETS = [
  ...GRID_TELEPORT_PRESETS,
  {
    key: DEFAULT_LOCATION_TELEPORT_KEY,
    label: 'Default location access (never shared)',
    latitude: DEFAULT_LOCATION_COORDINATES.latitude,
    longitude: DEFAULT_LOCATION_COORDINATES.longitude,
    accuracy: 15,
    statusMessage: 'Location reset to the default debug coordinates.'
  }
];

export const SPOOF_STEP_METERS = DEFAULT_SPOOF_STEP_MILES * METERS_PER_MILE;
export const DIRECTION_SUCCESS_MESSAGES = {
  north: `Moved north by roughly ${DEFAULT_SPOOF_STEP_MILES} mile${DEFAULT_SPOOF_STEP_MILES === 1 ? '' : 's'}.`,
  south: `Moved south by roughly ${DEFAULT_SPOOF_STEP_MILES} mile${DEFAULT_SPOOF_STEP_MILES === 1 ? '' : 's'}.`,
  east: `Moved east by roughly ${DEFAULT_SPOOF_STEP_MILES} mile${DEFAULT_SPOOF_STEP_MILES === 1 ? '' : 's'}.`,
  west: `Moved west by roughly ${DEFAULT_SPOOF_STEP_MILES} mile${DEFAULT_SPOOF_STEP_MILES === 1 ? '' : 's'}.`
};

export { METERS_PER_MILE };

export const JSON_PREVIEW_SX = {
  mt: 2,
  p: 2,
  borderRadius: 2,
  overflowX: 'auto',
  color: 'var(--color-text-primary)'
};

export const EXPERIMENT_ENABLED =
  runtimeConfig.troyExperimentEnabled && EXPERIMENT_SCREENS.length > 0;
